import 'package:flutter/material.dart';

List sad_quotes = [
  '"There are moments when I wish I could roll back the clock and take all the sadness away, but I have the feeling that if I did, the joy would be gone as well." –Nicholas Sparks',
  '"Life\'s under no obligation to give us what we expect." –Margaret Mitchell',
  '"You see, I usually find myself among strangers because I drift here and there trying to forget the sad things that happened to me." –F. Scott Fitzgerald',
  '"Don\'t go around saying the world owes you a living. The world owes you nothing. It was here first." –Mark Twain',
  '"Things change. And friends leave. And life doesn\'t stop for anybody." –Stephen Chbosky',
  '"Life is a moderately good play with a badly written third act." –Truman Capote',
  '"I have learned now that while those who speak about one\'s miseries usually hurt, those who keep silence hurt more." –C.S. Lewis',
  '"The excursion is the same when you go looking for your sorrow as when you go looking for your joy." –Eudora Welty',
  '"Don\'t ever tell anybody anything. If you do, you start missing everybody." –J.D. Salinger',
  '"So it\'s true, when all is said and done, grief is the price we pay for love." –E.A. Bucchianeri',
  '"What is hardest to accept about the passage of time is that the people who once mattered the most to us wind up in parentheses." –John Irving',
  '"Our dead are never dead to us until we have forgotten them." –George Eliot',
  '"The bitterest tears shed over graves are for words left unsaid and deeds left undone." –Harriet Beecher Stowe',
  '"It is the unknown we fear when we look upon death and darkness, nothing more." –J.K. Rowling',
  '"It\'s sad when someone you know becomes someone you knew." –Henry Rollins',
  '"There is a time for departure, even when there\'s no certain place to go." –Tennessee Williams',
  '"You meet everyone twice in this life, when they come and when they go." –C.C Aurel',
  '"Grief is not as heavy as guilt, but it takes more away from you." ­–Veronica Roth',
  '"Death is a great revealer of what is in a man, and in its solemn shadow appear the naked lineaments of the soul." –E.H. Chapin',
  '"Death is the dropping of the flower that the fruit may swell." –Henry Ward Beecher',
  '"You know, a heart can be broken, but it keeps on beating, just the same." –Fannie Flagg',
  '"It\'s amazing how someone can break your heart, and you can still love them with all the little pieces." –Ella Harper',
  '"There is a distinct, awful pain that comes with loving someone more than they love you." –Steve Maraboli',
  '"To have been loved so deeply, even though the person who loved us is gone, will give us some protection forever." –J.K. Rowling',
  '"If you gave someone your heart and they died, did they take it with them? Did you spend the rest of forever with a hole inside you that couldn\'t be filled?" –Jodi Picoult',
  '"You make me feel like a firefly. Trapped in a belljar; starved for love." –Ayushee Ghoshal',
  '"You\'re like a song that I heard when I was a little kid but forgot I knew until I heard it again." –Maggie Stiefvater',
  '"There is no greater sorrow than to recall, in misery, the time when we were happy." –Dante AligherI',
  '"Sometimes you got to hurt something to help something. Sometimes you have to plow under one thing in order for something else to grow." –Ernest J. Gaines',
  '"Tears are words the mouth can\'t say nor can the heart bear." –Joshua Wisenbaker',
  '"Being a successful person is not necessarily defined by what you have achieved, but by what you have overcome." –Fannie Flagg',
  '"To have felt too much is to end in feeling nothing." –Dorothy Thompson',
  '"One thing you can\'t hide is when you\'re crippled inside." –John Lennon',
  '"There are years that ask questions and years that answer." –Zora Neale Hurston',
  '"Heavy hearts, like heavy clouds in the sky, are best relieved by the letting of a little water." –Christopher Morley',
  '"Tears come from the heart and not from the brain." –Leonardo da Vinci'
];

List happy_quotes = [
  '"Happiness cannot be traveled to, owned, earned, worn or consumed. Happiness is the spiritual experience of living every minute with love, grace, and gratitude" -Denis Waitley',
  '"Some cause happiness wherever they go; others whenever they go. -Oscar Wilde"',
  '"Be healthy and take care of yourself, but be happy with the beautiful things that make you, you. -Beyoncé"',
  '"Most folks are about as happy as they make up their minds to be. -Abraham Lincoln"',
  '"For every minute you are angry you lose sixty seconds of happiness. -Ralph Waldo Emerson"',
  '"The biggest adventure you can ever take is to live the life of your dreams. -Oprah Winfrey"',
  '"Optimism is a happiness magnet. If you stay positive, good things and good people will be drawn to you. -Mary Lou Retton"',
  '"Everything has its wonders, even darkness and silence, and I learn, whatever state I may be in, therein to be content. -Helen Keller"',
  '"There is only one way to happiness and that is to cease worrying about things which are beyond the power of our will. -Epictetus"',
  '"Cry. Forgive. Learn. Move on. Let your tears water the seeds of your future happiness. -Steve Marabol"',
  '"The happiest people seem to be those who have no particular cause for being happy except that they are so. -William Ralph Inge"',
  '"Every day is a new day. -Carrie Underwood"',
  '"Beauty is everywhere. You only have to look to see it. -Bob Ross"',
  '"You can’t stop the waves, but you can learn to swim. -Jon Kabat Zinn"',
  '"Life is the dancer and you are the dance. -Eckhart Tolle"',
  '"Count your age by friends, not years. Count your life by smiles, not tears. -John Lennon"',
  '"The point is not to pay back kindness but to pass it on. -Julia Alvarez"',
  '"No medicine cures what happiness cannot. -Gabriel García Márquez"',
  '"When you love what you have, you have everything you need. -Unknown"',
  '"If you have only one smile in you give it to the people you love. -Maya Angelou"',
  '"The most important thing is to enjoy your life — to be happy. It\'s all that matters. -Audrey Hepburn"',
  '"The purpose of our lives is to be happy. -Dalai Lama"',
  '"Embrace the glorious mess that you are. -Elizabeth Gilbert"',
  '"Being happy never goes out of style. -Lilly Pulitzer"',
  '"Happiness is the best makeup. -Drew Barrymore"',
  '"Roll with the punches and enjoy every minute of it. -Meghan Markle"',
  '"The mere sense of living is joy enough. -Emily Dickinson"',
  '"The only thing that will make you happy is being happy with who you are. -Goldie Hawn"',
  '"Happiness comes in waves. It\'ll find you again. -Unknown"',
  '"If you want to be happy, be. -Leo Tolstoy"'
];

List surprise_quotes = [
  '"Moments of happiness come with the unexpected."',
  '"There is power in surprising people with results."',
  '"Life finds worth in surprises."',
  '"Surprising oneself is the greatest form of surprise."',
  '"Surprise always goes two ways."',
  '"Surprise the best element of humor."',
  '"Life itself is a surprise."',
  '"We should dwell on the positivity that comes as a surprise."',
  '"Accepting surprise is a way of having a joyful life."',
  '"Surprises never end."',
  '"Life is full of surprises."',
  '"Change sometimes comes as a surprise."',
  '"Being surprised should be far from the mind of a politician."',
  '"We should always be prepared for anything."',
  '"A surprise assault should be dealt with wit."',
  '"Surprise is one of the ways you find the person that is right for you."',
  '"Surprising ourselves is more empowering than surprising others."',
  '"Make the time that you have count."',
  '"There is fun in surprises."',
  '"Surprises can have better outcomes than what you know."',
  '"Live your life as if every hour you breathe is unexpected."',
  '"Expecting nothing opens you up for many possibilities."',
  '"Surprises are infinite."',
  '"We should always be ready for the unexpected."',
  '"Some surprises define us."',
  '"Vulnerability opens us up to tapping into our maximum performance."',
  '"Surprise can be a determinant of knowledge."',
  '"There is power in not knowing what will come next."',
  '"Defying expectations to open us up for surprises."',
  '"Accepting the truth is the first step toward making decisions."'
];

List angry_quotes = [
  '“Anger is like a storm rising up from the bottom of your consciousness. When you feel it coming, turn your focus to your breath.” – Thich Nhat Hanh',
  '“Speak when you are angry and you will make the best speech you will ever regret.” – Ambrose Bierce',
  '“Expressing anger is necessary.” – Jenny Holzer',
  '“Generally speaking, if a human being never shows anger, then I think something’s wrong. He’s not right in the brain.” – Dalai Lama',
  '“If we wish to express anger fully, the first step is to divorce the other person from any responsibility for our anger.” – Marshall Rosenberg',
  '“Anybody can become angry – that is easy, but to be angry with the right person and to the right degree and at the right time and for the right purpose, and in the right way – that is not within everybody’s power and is not easy.” – Aristotle',
  '“Angry people are not always wise.” – Jane Austen',
  '“Fools give full vent to their rage, but the wise bring calm in the end.” – Proverbs 29:11',
  '“There are two things a person should never be angry at, what they can help, and what they cannot.” – Plato',
  '“Anger is the feeling that makes your mouth work faster than your mind.” – Evan Esar',
  '“For every minute you remain angry, you give up sixty seconds of peace of mind.” – Ralph Waldo Emerson',
  '“If you try to get rid of fear and anger without knowing their meaning, they will grow stronger and return.” – Deepak Chopra',
  '“Anger is an acid that can do more harm to the vessel in which it is stored than to anything on which it is poured.” – Mark Twain',
  '“Get mad, then get over it.” – Colin Powell',
  '“Do not be quickly provoked in your spirit, for anger resides in the lap of fools.” – Ecclesiastes 7:9',
  '“Never respond to an angry person with a fiery comeback, even if he deserves it… Don’t allow his anger to become your anger.” – Bohdi Sanders',
  '“Don’t waste your time in anger, regrets, worries and grudges. Life is too short to be unhappy.” – Roy T. Bennett',
  '“You will not be punished for your anger, you will be punished by your anger.” – Buddha',
  '“Never go to bed mad. Stay up and fight.” – Phyllis Diller',
  '“Most misunderstandings in the world could be avoided if people would simply take the time to ask, ‘What else could this mean?’” – Shannon Alder',
  '“Don’t hold to anger, hurt or pain. They steal your energy and keep you from love.” – Leo Buscaglia',
  '“Anger makes you smaller, while forgiveness forces you to grow beyond what you are.” – Cherie Carter-Scott',
  '“To forgive is the highest, most beautiful form of love. In return, you will receive untold peace and happiness.” – Robert Muller',
  '“Be angry, and yet do not sin; do not let the sun go down on your anger.” – Henry Ward Beecher',
  '“When anger rises, think of the consequences.” – Confucius',
  '“Being unable to control your temper is no less of an illness than being anxious or depressed, and it deserves every bit as much sympathy.” – John Crawford',
  '“I believe that things should be let go once they are discussed. Apology accepted. End of story.” – Brad Goreski',
  '“Letting go gives us freedom, and freedom is the only condition for happiness. If, in our heart, we still cling to anything—anger, anxiety, or possessions—we cannot be free.” – Thich Nhat Hanh',
  '“The more anger towards the past you carry in your heart, the less capable you are of loving in the present.” – Barbara De Angelis',
  '“Learn this from me. Holding anger is a poison. It eats you from inside. We think that hating is a weapon that attacks the person who harmed us. But hatred is a curved blade. And the harm we do, we do to ourselves.” – Mitch Album',
];

List fear_quotes = [
  '”If you want to conquer fear, don’t sit home and think about it. Go out and get busy.” – Dale Carnegie',
  '”You gain strength, courage, and confidence by every experience in which you really stop to look fear in the face. You are able to say to yourself, ‘I lived through this horror. I can take the next thing that comes along.” – Eleanor Roosevelt',
  '”Don’t let fear or insecurity stop you from trying new things. Believe in yourself. Do what you love. And most importantly, be kind to others, even if you don’t like them.” – Stacy London',
  '”I learned that courage was not the absence of fear, but the triumph over it. The brave man is not he who does not feel afraid, but he who conquers that fear.” – Nelson Mandela',
  '”We must build dikes of courage to hold back the flood of fear.” – Martin Luther King, Jr.',
  '“You always have two choices: your commitment versus your fear.” – Sammy Davis, Jr.',
  '”As soon as the fear approaches near, attack and destroy it.” – Chanakya',
  '”Nothing in life is to be feared, it is only to be understood. Now is the time to understand more, so that we may fear less.” – Marie Curie',
  '”If you know the enemy and know yourself you need not fear the results of a hundred battles.” – Sun Tzu',
  '”The eagle has no fear of adversity. We need to be like the eagle and have a fearless spirit of a conqueror! “ – Joyce Meyer',
  '”Living with fear stops us taking risks, and if you don’t go out on the branch, you’re never going to get the best fruit.” – Sarah Parish',
  '”Fear doesn’t exist anywhere except in the mind.” – Dale Carnegie',
  '”Expose yourself to your deepest fear; after that, fear has no power, and the fear of freedom shrinks and vanishes. You are free.” – Jim Morrison',
  '”Fear not, we are of the nature of the lion, and cannot descend to the destruction of mice and such small beasts.” – Elizabeth I',
  '”I have learned over the years that when one’s mind is made up, this diminishes fear; knowing what must be done does away with fear.” – Rosa Parks',
  '”Being brave isn’t the absence of fear. Being brave is having that fear but finding a way through it.” –  Bear Grylls',
  '”The key to growth is acknowledging your fear of the unknown and jumping in anyway.” – Jen Sincero',
  '”You just have to get rid of fear and confront the world. Look at yourself in the mirror and say to yourself, ‘I love you and nothing will destroy you and you’re not going to fall.” – Ricky Martin',
  '”If you go deeper and deeper into your own heart, you’ll be living in a world with less fear, isolation and loneliness.” – Sharon Salzberg',
  '”I was set free because my greatest fear had been realized, and I still had a daughter who I adored, and I had an old typewriter and a big idea. And so rock bottom became a solid foundation on which I rebuilt my life.” – J. K. Rowling',
  '”Never let the fear of striking out get in your way.” – Babe Ruth',
  'I believe that every single event in life happens in an opportunity to choose love over fear.” – Oprah Winfrey',
  '”The key to success is to focus our conscious mind on things we desire not things we fear.” – Brian Tracy',
  '”He who is not every day conquering some fear has not learned the secret of life.” – Ralph Waldo Emerson',
  '”Kill the snake of doubt in your soul, crush the worms of fear in your heart and mountains will move out of your way.” – Kate Seredy',
  'I have a very positive attitude in life. My insecurity, fear and need to know about tomorrow has fortunately eased. What is going to happen will happen anyway. So why break my head over it?” – Katrina Kaif',
  '”Fear is stupid. So are regrets.” – Marilyn Monroe',
  '”Don’t fear failure so much that you refuse to try new things. The saddest summary of a life contains three descriptions: could have, might have, and should have.” – Louis E. Boone',
  '”Fear is the main source of superstition, and one of the main sources of cruelty. To conquer fear is the beginning of wisdom.” – Bertrand Russell',
  '”How very little can be done under the spirit of fear.” – Florence Nightingale'
];

List neutral_quotes = [
  "The only way to do great work is to love what you do. - Steve Jobs",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
  "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
  "The best way to predict the future is to create it. - Peter Drucker",
  "In the middle of difficulty lies opportunity. - Albert Einstein",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "Happiness is not something ready-made. It comes from your own actions. - Dalai Lama",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
  "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
  "The secret of getting ahead is getting started. - Mark Twain",
  "The best revenge is massive success. - Frank Sinatra",
  "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
  "The only person you should try to be better than is the person you were yesterday. - Matty Mullins",
  "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "The harder I work, the luckier I get. - Gary Player",
  "The man who moves a mountain begins by carrying away small stones. - Confucius",
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "Life is really simple, but we insist on making it complicated. - Confucius",
  "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. - Ralph Waldo Emerson",
  "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart. - Helen Keller",
  "The only way to do great work is to love what you do. - Steve Jobs",
  "Do what you can, with what you have, where you are. - Theodore Roosevelt",
  "We don't see things as they are, we see them as we are. - Anaïs Nin",
  "Change your thoughts and you change your world. - Norman Vincent Peale",
  "Every strike brings me closer to the next home run. - Babe Ruth",
  "It always seems impossible until it's done. - Nelson Mandela",
  "Life is really simple, but we insist on making it complicated. - Confucius",
  "The only true wisdom is in knowing you know nothing. - Socrates"
];

List disgust_quotes = [
  "Disgust is the instinctive revulsion we feel towards anything that might threaten our health or survival. - Paul Rozin",
  "Disgust is nature's way of protecting us from potential dangers. - Valerie Curtis",
  "Disgust is the emotional reaction to the violation of our internal sense of purity and cleanliness. - Martha Nussbaum",
  "Disgust is the proper response to moral and ethical violations. - Jonathan Haidt",
  "Disgust is a powerful tool that helps us avoid harmful substances and situations. - Daniel Kelly",
  "Disgust is the emotion that signals our boundaries and helps us define what is acceptable and what is not. - Rachel Herz",
  "Disgust is a way for us to distance ourselves from things that we find morally or socially repugnant. - Susan Fiske",
  "Disgust is a basic human emotion that serves an important evolutionary function. - Virginia M. Y. Lee",
  "Disgust is the emotion that arises when we encounter something that violates our expectations and beliefs. - David Pizarro",
  "Disgust is an emotion that reflects our sense of taste and what we find unappetizing. - Emily Nussbaum",
  "Disgust is an emotion that can be learned and influenced by culture. - Paul Ekman",
  "Disgust is a complex emotion that involves both sensory and cognitive processes. - Alan Page Fiske",
  "Disgust can be a powerful motivator for social change when directed at injustice and inequality. - Martha C. Nussbaum",
  "Disgust is the emotional response that helps us avoid contamination and disease. - Rachel Herz",
  "Disgust is a deeply rooted emotion that is closely tied to our survival instincts. - David Buss",
  "Disgust is the emotion that emerges when we encounter something that challenges our sense of order and cleanliness. - Mary Douglas",
  "Disgust can be a way of asserting power and dominance over others. - Michael Billig",
  "Disgust is an emotion that can vary across cultures and individuals. - Daniel M.T. Fessler",
  "Disgust can be a catalyst for moral judgments and the pursuit of justice. - June Price Tangney",
  "Disgust is the emotion that reminds us of our vulnerability and mortality. - Martha Nussbaum",
  "Disgust is an evolutionary adaptation that helps us avoid potential sources of disease and infection. - Paul Rozin",
  "Disgust is the emotion that highlights the limits of our tolerance and acceptance. - Peter Rozin",
  "Disgust is a complex emotion that can be influenced by our upbringing, experiences, and personal beliefs. - Valerie Curtis",
  "Disgust is the emotion that reminds us of our shared humanity and our capacity for empathy. - David Livingstone Smith",
  "Disgust is a natural response to behaviors and situations that threaten our social order and norms. - Jennifer Jacquet",
  "Disgust is an emotion that helps us navigate the moral complexities of life. - Paul Bloom",
  "Disgust is a protective emotion that shields us from potential harm. - Martha Nussbaum",
  "Disgust is the emotion that alerts us to potential dangers and helps us make informed decisions. - Rachel Herz",
  "Disgust is the emotional response that separates the acceptable from the unacceptable. - Valerie Curtis",
];
